// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoDw7CAqPC1PkhHfkx8FpmvP_Q9CKxL6U',
    appId: '1:1077979228133:web:842dc2047c2e524652710c',
    messagingSenderId: '1077979228133',
    projectId: 'flutter-mvvm-gamer-1c6c9',
    authDomain: 'flutter-mvvm-gamer-1c6c9.firebaseapp.com',
    storageBucket: 'flutter-mvvm-gamer-1c6c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHKL0Bmu3uz8mfAFhPZGfOrOHsBqH5vuo',
    appId: '1:1077979228133:android:ad16d68cb8c5f41552710c',
    messagingSenderId: '1077979228133',
    projectId: 'flutter-mvvm-gamer-1c6c9',
    storageBucket: 'flutter-mvvm-gamer-1c6c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsMjsbQqIOHruUihQyeRvRf01JfXGLOnM',
    appId: '1:1077979228133:ios:2208fda0d922cfce52710c',
    messagingSenderId: '1077979228133',
    projectId: 'flutter-mvvm-gamer-1c6c9',
    storageBucket: 'flutter-mvvm-gamer-1c6c9.appspot.com',
    iosBundleId: 'com.example.flutterGamerMvvm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsMjsbQqIOHruUihQyeRvRf01JfXGLOnM',
    appId: '1:1077979228133:ios:2208fda0d922cfce52710c',
    messagingSenderId: '1077979228133',
    projectId: 'flutter-mvvm-gamer-1c6c9',
    storageBucket: 'flutter-mvvm-gamer-1c6c9.appspot.com',
    iosBundleId: 'com.example.flutterGamerMvvm',
  );
}
